# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MORZEENCODER.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 375)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 700, 200))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                 "border-style: solid;\n"
                                 "border-color: rgb(0, 255, 0);\n"
                                 "border-width: 1px;\n"
                                 "color: rgb(0, 255, 0);")
        self.label.setObjectName("label")
        self.a_button = QtWidgets.QPushButton(self.centralwidget)
        self.a_button.setGeometry(QtCore.QRect(0, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.a_button.setFont(font)
        self.a_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.a_button.setObjectName("a_button")
        self.b_button = QtWidgets.QPushButton(self.centralwidget)
        self.b_button.setGeometry(QtCore.QRect(200, 300, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.b_button.setFont(font)
        self.b_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.b_button.setObjectName("b_button")
        self.q_button = QtWidgets.QPushButton(self.centralwidget)
        self.q_button.setGeometry(QtCore.QRect(0, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.q_button.setFont(font)
        self.q_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.q_button.setObjectName("q_button")
        self.w_button = QtWidgets.QPushButton(self.centralwidget)
        self.w_button.setGeometry(QtCore.QRect(50, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.w_button.setFont(font)
        self.w_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.w_button.setObjectName("w_button")
        self.e_button = QtWidgets.QPushButton(self.centralwidget)
        self.e_button.setGeometry(QtCore.QRect(100, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.e_button.setFont(font)
        self.e_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.e_button.setObjectName("e_button")
        self.r_button = QtWidgets.QPushButton(self.centralwidget)
        self.r_button.setGeometry(QtCore.QRect(150, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.r_button.setFont(font)
        self.r_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.r_button.setObjectName("r_button")
        self.t_button = QtWidgets.QPushButton(self.centralwidget)
        self.t_button.setGeometry(QtCore.QRect(200, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.t_button.setFont(font)
        self.t_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.t_button.setObjectName("t_button")
        self.y_button = QtWidgets.QPushButton(self.centralwidget)
        self.y_button.setGeometry(QtCore.QRect(250, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.y_button.setFont(font)
        self.y_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.y_button.setObjectName("y_button")
        self.u_button = QtWidgets.QPushButton(self.centralwidget)
        self.u_button.setGeometry(QtCore.QRect(300, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.u_button.setFont(font)
        self.u_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.u_button.setObjectName("u_button")
        self.i_button = QtWidgets.QPushButton(self.centralwidget)
        self.i_button.setGeometry(QtCore.QRect(350, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.i_button.setFont(font)
        self.i_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.i_button.setObjectName("i_button")
        self.o_button = QtWidgets.QPushButton(self.centralwidget)
        self.o_button.setGeometry(QtCore.QRect(400, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.o_button.setFont(font)
        self.o_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.o_button.setObjectName("o_button")
        self.p_button = QtWidgets.QPushButton(self.centralwidget)
        self.p_button.setGeometry(QtCore.QRect(450, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.p_button.setFont(font)
        self.p_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.p_button.setObjectName("p_button")
        self.s_button = QtWidgets.QPushButton(self.centralwidget)
        self.s_button.setGeometry(QtCore.QRect(50, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.s_button.setFont(font)
        self.s_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.s_button.setObjectName("s_button")
        self.d_button = QtWidgets.QPushButton(self.centralwidget)
        self.d_button.setGeometry(QtCore.QRect(100, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.d_button.setFont(font)
        self.d_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.d_button.setObjectName("d_button")
        self.f_button = QtWidgets.QPushButton(self.centralwidget)
        self.f_button.setGeometry(QtCore.QRect(150, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.f_button.setFont(font)
        self.f_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.f_button.setObjectName("f_button")
        self.g_button = QtWidgets.QPushButton(self.centralwidget)
        self.g_button.setGeometry(QtCore.QRect(200, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.g_button.setFont(font)
        self.g_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.g_button.setObjectName("g_button")
        self.h_button = QtWidgets.QPushButton(self.centralwidget)
        self.h_button.setGeometry(QtCore.QRect(250, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.h_button.setFont(font)
        self.h_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.h_button.setObjectName("h_button")
        self.j_button = QtWidgets.QPushButton(self.centralwidget)
        self.j_button.setGeometry(QtCore.QRect(300, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.j_button.setFont(font)
        self.j_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.j_button.setObjectName("j_button")
        self.k_button = QtWidgets.QPushButton(self.centralwidget)
        self.k_button.setGeometry(QtCore.QRect(350, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.k_button.setFont(font)
        self.k_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.k_button.setObjectName("k_button")
        self.l_button = QtWidgets.QPushButton(self.centralwidget)
        self.l_button.setGeometry(QtCore.QRect(400, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.l_button.setFont(font)
        self.l_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.l_button.setObjectName("l_button")
        self.z_button = QtWidgets.QPushButton(self.centralwidget)
        self.z_button.setGeometry(QtCore.QRect(0, 300, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.z_button.setFont(font)
        self.z_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.z_button.setObjectName("z_button")
        self.x_button = QtWidgets.QPushButton(self.centralwidget)
        self.x_button.setGeometry(QtCore.QRect(50, 300, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.x_button.setFont(font)
        self.x_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.x_button.setObjectName("x_button")
        self.c_button = QtWidgets.QPushButton(self.centralwidget)
        self.c_button.setGeometry(QtCore.QRect(100, 300, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.c_button.setFont(font)
        self.c_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.c_button.setObjectName("c_button")
        self.v_button = QtWidgets.QPushButton(self.centralwidget)
        self.v_button.setGeometry(QtCore.QRect(150, 300, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.v_button.setFont(font)
        self.v_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.v_button.setObjectName("v_button")
        self.n_button = QtWidgets.QPushButton(self.centralwidget)
        self.n_button.setGeometry(QtCore.QRect(250, 300, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.n_button.setFont(font)
        self.n_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.n_button.setObjectName("n_button")
        self.m_button = QtWidgets.QPushButton(self.centralwidget)
        self.m_button.setGeometry(QtCore.QRect(300, 300, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.m_button.setFont(font)
        self.m_button.setStyleSheet("QPushButton {\n"
                                    "    color: rgb(0, 255, 0);\n"
                                    "    background-color: rgb(0, 0, 0);\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(128, 128, 128);\n"
                                    "}")
        self.m_button.setObjectName("m_button")
        self.one_button = QtWidgets.QPushButton(self.centralwidget)
        self.one_button.setGeometry(QtCore.QRect(500, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.one_button.setFont(font)
        self.one_button.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(0, 255, 0);\n"
                                      "    background-color: rgb(0, 0, 0);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(128, 128, 128);\n"
                                      "}")
        self.one_button.setObjectName("one_button")
        self.zero_button = QtWidgets.QPushButton(self.centralwidget)
        self.zero_button.setGeometry(QtCore.QRect(650, 250, 50, 100))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.zero_button.setFont(font)
        self.zero_button.setStyleSheet("QPushButton {\n"
                                       "    color: rgb(0, 255, 0);\n"
                                       "    background-color: rgb(0, 0, 0);\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(128, 128, 128);\n"
                                       "}")
        self.zero_button.setObjectName("zero_button")
        self.eight_button = QtWidgets.QPushButton(self.centralwidget)
        self.eight_button.setGeometry(QtCore.QRect(600, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.eight_button.setFont(font)
        self.eight_button.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(0, 255, 0);\n"
                                        "    background-color: rgb(0, 0, 0);\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(128, 128, 128);\n"
                                        "}")
        self.eight_button.setObjectName("eight_button")
        self.seven_button = QtWidgets.QPushButton(self.centralwidget)
        self.seven_button.setGeometry(QtCore.QRect(600, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.seven_button.setFont(font)
        self.seven_button.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(0, 255, 0);\n"
                                        "    background-color: rgb(0, 0, 0);\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(128, 128, 128);\n"
                                        "}")
        self.seven_button.setObjectName("seven_button")
        self.six_button = QtWidgets.QPushButton(self.centralwidget)
        self.six_button.setGeometry(QtCore.QRect(550, 300, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.six_button.setFont(font)
        self.six_button.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(0, 255, 0);\n"
                                      "    background-color: rgb(0, 0, 0);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(128, 128, 128);\n"
                                      "}")
        self.six_button.setObjectName("six_button")
        self.five_button = QtWidgets.QPushButton(self.centralwidget)
        self.five_button.setGeometry(QtCore.QRect(550, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.five_button.setFont(font)
        self.five_button.setStyleSheet("QPushButton {\n"
                                       "    color: rgb(0, 255, 0);\n"
                                       "    background-color: rgb(0, 0, 0);\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(128, 128, 128);\n"
                                       "}")
        self.five_button.setObjectName("five_button")
        self.four_button = QtWidgets.QPushButton(self.centralwidget)
        self.four_button.setGeometry(QtCore.QRect(550, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.four_button.setFont(font)
        self.four_button.setStyleSheet("QPushButton {\n"
                                       "    color: rgb(0, 255, 0);\n"
                                       "    background-color: rgb(0, 0, 0);\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(128, 128, 128);\n"
                                       "}")
        self.four_button.setObjectName("four_button")
        self.three_button = QtWidgets.QPushButton(self.centralwidget)
        self.three_button.setGeometry(QtCore.QRect(500, 300, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.three_button.setFont(font)
        self.three_button.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(0, 255, 0);\n"
                                        "    background-color: rgb(0, 0, 0);\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(128, 128, 128);\n"
                                        "}")
        self.three_button.setObjectName("three_button")
        self.two_button = QtWidgets.QPushButton(self.centralwidget)
        self.two_button.setGeometry(QtCore.QRect(500, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.two_button.setFont(font)
        self.two_button.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(0, 255, 0);\n"
                                      "    background-color: rgb(0, 0, 0);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(128, 128, 128);\n"
                                      "}")
        self.two_button.setObjectName("two_button")
        self.nine_button = QtWidgets.QPushButton(self.centralwidget)
        self.nine_button.setGeometry(QtCore.QRect(600, 300, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.nine_button.setFont(font)
        self.nine_button.setStyleSheet("QPushButton {\n"
                                       "    color: rgb(0, 255, 0);\n"
                                       "    background-color: rgb(0, 0, 0);\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(128, 128, 128);\n"
                                       "}")
        self.nine_button.setObjectName("nine_button")
        self.space_button = QtWidgets.QPushButton(self.centralwidget)
        self.space_button.setGeometry(QtCore.QRect(450, 250, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.space_button.setFont(font)
        self.space_button.setStyleSheet("QPushButton {\n"
                                        "    color: rgb(0, 255, 0);\n"
                                        "    background-color: rgb(0, 0, 0);\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "    background-color: rgb(128, 128, 128);\n"
                                        "}")
        self.space_button.setObjectName("space_button")
        self.go_button = QtWidgets.QPushButton(self.centralwidget)
        self.go_button.setGeometry(QtCore.QRect(350, 300, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.go_button.setFont(font)
        self.go_button.setStyleSheet("QPushButton {\n"
                                     "    color: rgb(0, 255, 0);\n"
                                     "    background-color: rgb(0, 0, 0);\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "    background-color: rgb(128, 128, 128);\n"
                                     "}")
        self.go_button.setObjectName("go_button")
        self.del_button = QtWidgets.QPushButton(self.centralwidget)
        self.del_button.setGeometry(QtCore.QRect(650, 200, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.del_button.setFont(font)
        self.del_button.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(0, 255, 0);\n"
                                      "    background-color: rgb(0, 0, 0);\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(128, 128, 128);\n"
                                      "}")
        self.del_button.setObjectName("del_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Morze_Encoder"))
        self.label.setText(_translate("MainWindow", "ENTER TEXT >>>"))
        self.a_button.setText(_translate("MainWindow", "A"))
        self.b_button.setText(_translate("MainWindow", "B"))
        self.q_button.setText(_translate("MainWindow", "Q"))
        self.w_button.setText(_translate("MainWindow", "W"))
        self.e_button.setText(_translate("MainWindow", "E"))
        self.r_button.setText(_translate("MainWindow", "R"))
        self.t_button.setText(_translate("MainWindow", "T"))
        self.y_button.setText(_translate("MainWindow", "Y"))
        self.u_button.setText(_translate("MainWindow", "U"))
        self.i_button.setText(_translate("MainWindow", "I"))
        self.o_button.setText(_translate("MainWindow", "O"))
        self.p_button.setText(_translate("MainWindow", "P"))
        self.s_button.setText(_translate("MainWindow", "S"))
        self.d_button.setText(_translate("MainWindow", "D"))
        self.f_button.setText(_translate("MainWindow", "F"))
        self.g_button.setText(_translate("MainWindow", "G"))
        self.h_button.setText(_translate("MainWindow", "H"))
        self.j_button.setText(_translate("MainWindow", "J"))
        self.k_button.setText(_translate("MainWindow", "K"))
        self.l_button.setText(_translate("MainWindow", "L"))
        self.z_button.setText(_translate("MainWindow", "Z"))
        self.x_button.setText(_translate("MainWindow", "X"))
        self.c_button.setText(_translate("MainWindow", "C"))
        self.v_button.setText(_translate("MainWindow", "V"))
        self.n_button.setText(_translate("MainWindow", "N"))
        self.m_button.setText(_translate("MainWindow", "M"))
        self.one_button.setText(_translate("MainWindow", "1"))
        self.zero_button.setText(_translate("MainWindow", "0"))
        self.eight_button.setText(_translate("MainWindow", "8"))
        self.seven_button.setText(_translate("MainWindow", "7"))
        self.six_button.setText(_translate("MainWindow", "6"))
        self.five_button.setText(_translate("MainWindow", "5"))
        self.four_button.setText(_translate("MainWindow", "4"))
        self.three_button.setText(_translate("MainWindow", "3"))
        self.two_button.setText(_translate("MainWindow", "2"))
        self.nine_button.setText(_translate("MainWindow", "9"))
        self.space_button.setText(_translate("MainWindow", "\' \'"))
        self.go_button.setText(_translate("MainWindow", "ENCODE >>>"))
        self.del_button.setText(_translate("MainWindow", "DEL"))

        self.label.setText('')

    def add_functions(self):
        self.zero_button.clicked.connect(lambda: self.write_symbol(self.zero_button.text()))
        self.one_button.clicked.connect(lambda: self.write_symbol(self.one_button.text()))
        self.two_button.clicked.connect(lambda: self.write_symbol(self.two_button.text()))
        self.three_button.clicked.connect(lambda: self.write_symbol(self.three_button.text()))
        self.four_button.clicked.connect(lambda: self.write_symbol(self.four_button.text()))
        self.five_button.clicked.connect(lambda: self.write_symbol(self.five_button.text()))
        self.six_button.clicked.connect(lambda: self.write_symbol(self.six_button.text()))
        self.seven_button.clicked.connect(lambda: self.write_symbol(self.seven_button.text()))
        self.eight_button.clicked.connect(lambda: self.write_symbol(self.eight_button.text()))
        self.nine_button.clicked.connect(lambda: self.write_symbol(self.nine_button.text()))
        self.a_button.clicked.connect(lambda: self.write_symbol(self.a_button.text()))
        self.b_button.clicked.connect(lambda: self.write_symbol(self.b_button.text()))
        self.c_button.clicked.connect(lambda: self.write_symbol(self.c_button.text()))
        self.d_button.clicked.connect(lambda: self.write_symbol(self.d_button.text()))
        self.e_button.clicked.connect(lambda: self.write_symbol(self.e_button.text()))
        self.f_button.clicked.connect(lambda: self.write_symbol(self.f_button.text()))
        self.g_button.clicked.connect(lambda: self.write_symbol(self.g_button.text()))
        self.h_button.clicked.connect(lambda: self.write_symbol(self.h_button.text()))
        self.i_button.clicked.connect(lambda: self.write_symbol(self.i_button.text()))
        self.j_button.clicked.connect(lambda: self.write_symbol(self.j_button.text()))
        self.k_button.clicked.connect(lambda: self.write_symbol(self.k_button.text()))
        self.l_button.clicked.connect(lambda: self.write_symbol(self.l_button.text()))
        self.m_button.clicked.connect(lambda: self.write_symbol(self.m_button.text()))
        self.n_button.clicked.connect(lambda: self.write_symbol(self.n_button.text()))
        self.o_button.clicked.connect(lambda: self.write_symbol(self.o_button.text()))
        self.p_button.clicked.connect(lambda: self.write_symbol(self.p_button.text()))
        self.q_button.clicked.connect(lambda: self.write_symbol(self.q_button.text()))
        self.r_button.clicked.connect(lambda: self.write_symbol(self.r_button.text()))
        self.s_button.clicked.connect(lambda: self.write_symbol(self.s_button.text()))
        self.t_button.clicked.connect(lambda: self.write_symbol(self.t_button.text()))
        self.u_button.clicked.connect(lambda: self.write_symbol(self.u_button.text()))
        self.v_button.clicked.connect(lambda: self.write_symbol(self.v_button.text()))
        self.w_button.clicked.connect(lambda: self.write_symbol(self.w_button.text()))
        self.x_button.clicked.connect(lambda: self.write_symbol(self.x_button.text()))
        self.y_button.clicked.connect(lambda: self.write_symbol(self.y_button.text()))
        self.z_button.clicked.connect(lambda: self.write_symbol(self.z_button.text()))
        self.space_button.clicked.connect(lambda: self.write_symbol(' '))
        self.del_button.clicked.connect(lambda: self.write_symbol(self.del_button.text()))
        self.go_button.clicked.connect(lambda: self.write_symbol(self.go_button.text()))

    def encode_func(self, text):
        morse_code_dict = {
                    'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.',
                    'F': '..-.', 'G': '--.', 'H': '....', 'I': '..', 'J': '.---',
                    'K': '-.-', 'L': '.-..', 'M': '--', 'N': '-.', 'O': '---',
                    'P': '.--.', 'Q': '--.-', 'R': '.-.', 'S': '...', 'T': '-',
                    'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-', 'Y': '-.--',
                    'Z': '--..',
                    '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....',
                    '6': '-....', '7': '--...', '8': '---..', '9': '----.', '0': '-----'
        }

        morse_code = []

        for char in text:
            if char in morse_code_dict:
                morse_code.append(morse_code_dict[char])
            else:
                morse_code.append(' ')

        return ' '.join(morse_code)

    def write_symbol(self, symbol):
        if symbol == 'DEL':
            if self.label.text() == '':
                pass
            else:
                self.label.setText(self.label.text()[:-1])
        elif symbol == 'ENCODE >>>':
            self.label.setText(self.encode_func(self.label.text()))
        else:
            self.label.setText(self.label.text() + symbol)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
